# golang
- name: create local golang directory
  file:
    path: ~/go
    state: directory

- name: include local golang bin in path
  lineinfile:
    dest: ~/.profile
    line: export PATH=$PATH:$HOME/go/bin

- name: alias hub as git
  lineinfile:
    dest: ~/.profile
    line: alias git=hub
