# Tmux
- name: link tmux.conf
  file:
    src: '{{ ansible_env.PWD }}/roles/aaron_common/files/tmux/tmux.conf'
    path: ~/.tmux.conf
    state: link
    force: yes
  tags: dotfiles

# Tmuxinator
- name: create tmuxinator config directory
  file:
    path: ~/.tmuxinator
    state: directory
  tags: dotfiles

- name: link tmuxinator session configurations
  file:
    src: '{{ ansible_env.PWD }}/roles/aaron_common/files/tmuxinator/{{ item }}'
    path: ~/.tmuxinator/{{ item }}
    state: link
    force: yes
  with_items:
    - tmuxinator.zsh
    - projects.yml
    - vertical.yml
    - work.yml
  tags: dotfiles

# Vim
- name: link vimrc
  file:
    src: '{{ ansible_env.PWD }}/roles/aaron_common/files/vim/vimrc'
    path: ~/.vimrc
    state: link
    force: yes
  tags: dotfiles

# Zsh
- name: link zsh
  file:
    src: '{{ ansible_env.PWD }}/roles/aaron_common/files/zsh/zshrc'
    path: ~/.zshrc
    state: link
    force: yes
  tags: dotfiles
