# Tmux
- name: link tmux.conf
  file:
    src: '{{ ansible_env.PWD }}/roles/aaron_common/files/tmux/tmux.conf'
    path: ~/.tmux.conf
    state: link
    force: yes
  tags: dotfiles,newuser

# Tmuxinator
- name: create tmuxinator config directory
  file:
    path: ~/.tmuxinator
    state: directory
  tags: dotfiles,newuser

- name: link tmuxinator session configurations
  file:
    src: '{{ ansible_env.PWD }}/roles/aaron_common/files/tmuxinator/{{ item }}'
    path: ~/.tmuxinator/{{ item }}
    state: link
    force: yes
  with_items:
    - tmuxinator.zsh
    - projects.yml
    - vertical.yml
    - work.yml
  tags: dotfiles,newuser

# Vim
- name: link vimrc
  file:
    src: '{{ ansible_env.PWD }}/roles/aaron_common/files/vim/vimrc'
    path: ~/.vimrc
    state: link
    force: yes
  tags: dotfiles,newuser

# Zsh
- name: link zsh
  file:
    src: '{{ ansible_env.PWD }}/roles/aaron_common/files/zsh/zshrc'
    path: ~/.zshrc
    state: link
    force: yes
  tags: dotfiles,newuser


# Firefox
- name: Get all firefox profile dirs
  shell: grep 'Path=' ~/Library/Application\ Support/Firefox/profiles.ini | sed 's/^Path=//'
  register: firefox_profile_dirs
  when: ansible_system == 'Darwin'
  tags: dotfiles,newuser

- name: create chrome directory under profile dirs
  file:
    path: ~/Library/Application Support/Firefox/{{ item }}/chrome
    state: directory
  loop: "{{ firefox_profile_dirs.stdout_lines }}"
  when: ansible_system == 'Darwin'
  tags: dotfiles,newuser

- name: Link userChrome.css under profile chrome dirs
  file:
    src: '{{ ansible_env.PWD }}/roles/aaron_common/files/firefox/userChrome.css'
    path: ~/Library/Application Support/Firefox/{{ item }}/chrome/userChrome.css
    state: link
    force: yes
  loop: "{{ firefox_profile_dirs.stdout_lines }}"
  when: ansible_system == 'Darwin'
  tags: dotfiles,newuser
