# pip
- name: Install pip packages
  pip:
    name: '{{ item }}'
    state: latest
    executable: pip3
  with_items: '{{ pip_packages }}'
  tags: pip

# npm
- name: Install root npm packages (OSX)
  npm:
    name: '{{ item }}'
    state: latest
    global: yes
  with_items: '{{ npm_root_packages }}'
  when: ansible_system == 'Darwin'
  tags: npm

- name: Install root npm packages (Linux)
  npm:
    name: '{{ item }}'
    state: latest
    global: yes
  with_items: '{{ npm_root_packages }}'
  when: ansible_system == 'Linux'
  become: yes
  tags: npm

# gem
- name: Install gem packages (OSX)
  gem:
    name: '{{ item }}'
    state: latest
    user_install: no
  with_items: '{{ gem_packages }}'
  when: ansible_system == 'Darwin'
  tags: gem

- name: Install gem packages (Linux)
  gem:
    name: '{{ item }}'
    state: latest
    user_install: no
  with_items: '{{ gem_packages }}'
  become: yes
  when: ansible_system == 'Linux'
  tags: gem
