# Install VSCode extensions using CLI - currently no support for a configuration file
- name: Get VSCode installed extensions
  shell: code --list-extensions
  register: vscode_installed_extensions

- name: Install missing VSCode extensions
  shell: 'code --install-extension {{ item }}'
  with_items: '{{ vscode_extensions }}'
  when: item not in vscode_installed_extensions.stdout_lines

# Link VSCode keybindings.json and settings.json
- when: ansible_system == 'Darwin'
  name: link vscode settings.json
  file:
    src: '{{ ansible_env.PWD }}/roles/aaron_common/files/vscode_{{ item }}'
    path: '~/Library/Application Support/Code/User/{{ item }}'
    state: link
    force: yes
  with_items:
    - keybindings.json
    - settings.json

- when: ansible_system == 'Linux'
  name: link vscode settings.json
  file:
    src: '{{ ansible_env.PWD }}/roles/aaron_common/files/vscode_{{ item }}'
    path: '~/.config/Code/User/{{ item }}'
    state: link
    force: yes
  with_items:
    - keybindings.json
    - settings.json
