#########################
###### Using zplug ######
#########################

# Check if zplug is installed
if [[ ! -d ~/.zplug ]]; then
  git clone https://github.com/zplug/zplug ~/.zplug
  source ~/.zplug/init.zsh && zplug update --self
fi

# Initialise zplug
source ~/.zplug/init.zsh

# Scripts
source ~/.tmuxinator/tmuxinator.zsh

#########################
# Plugins
#########################

# syntax highlighting and substring search
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-history-substring-search"

# fish-like auto suggestions
zplug "zsh-users/zsh-autosuggestions", from:github

# extra auto completions
zplug "zsh-users/zsh-completions", from:github

# osx helpers
zplug "unixorn/tumult.plugin.zsh", from:github

# warn when running command you have an alias for
zplug "djui/alias-tips", from:github

# git helper scripts
zplug "unixorn/git-extra-commands", from:github

# sysadmin helpers
zplug "skx/sysadmin-util", from:github

# open branch/files in github
zplug "peterhurford/git-it-on.zsh", from:github

# Prezto theme and plugins
zstyle ':prezto:module:*' color 'yes'
zstyle ':prezto:module:*' case-sensitive 'no'
zstyle ':prezto:module:prompt' theme sorin
zplug "modules/prompt", from:prezto
zplug "modules/directory", from:prezto
zplug "modules/editor", from:prezto
zplug "modules/git", from:prezto
zplug "modules/history", from:prezto
zplug "modules/utility", from:prezto

#########################

# Install packages that have not been installed yet
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    else
        echo
    fi
fi

zplug load
