# Homebrew
- homebrew_tap:
    tap: '{{ item }}'
  with_items: '{{ homebrew_taps }}'
  tags: brew

- homebrew:
    name: git
    state: latest
    update_homebrew: yes
  tags: brew

- homebrew:
    name: '{{ item }}'
    state: latest
  with_items: '{{ homebrew_packages }}'
  tags: brew

- homebrew:
    name: '{{ item }}'
    state: latest
  with_items: '{{ homebrew_packages_thread }}'
  tags: never,thread

- homebrew_cask:
    name: '{{ item }}'
    state: installed
  with_items: '{{ homebrew_cask_packages }}'
  tags: brew

- homebrew_cask:
    name: '{{ item }}'
    state: installed
  with_items: '{{ homebrew_cask_packages_personal }}'
  tags: never,personal

# Hammerspoon for window shortcuts
- name: link hammerspoon config
  file:
    src: '{{ ansible_env.PWD }}/roles/aaron_osx/files/hammerspoon'
    path: ~/.hammerspoon
    state: link
    force: yes
  tags: dotfiles,newuser
