# Homebrew
- homebrew_tap:
    tap: '{{ item }}'
  with_items: '{{ homebrew_taps }}'
  tags: brew

- homebrew:
    name: git
    state: latest
    update_homebrew: yes
  tags: brew

- homebrew:
    name: '{{ item }}'
    state: latest
  with_items: '{{ homebrew_packages }}'
  tags: brew

- homebrew:
    name: '{{ item }}'
    state: latest
  with_items: '{{ homebrew_packages_thread }}'
  tags: never,thread

- homebrew_cask:
    name: '{{ item }}'
    state: installed
  with_items: '{{ homebrew_cask_packages }}'
  tags: brew

- homebrew_cask:
    name: '{{ item }}'
    state: installed
  with_items: '{{ homebrew_cask_packages_personal }}'
  tags: never,personal

# Hammerspoon for window shortcuts
- name: link hammerspoon config
  file:
    src: '{{ ansible_env.PWD }}/roles/aaron_osx/files/hammerspoon'
    path: ~/.hammerspoon
    state: link
    force: yes
  tags: dotfiles,newuser

# Install keepassx directly from site (without cask just to be safe)
- local_action:
    module: stat
    path: /Applications/KeePassX.app
  register: keepassx_exists

- name: Import keepassx public key
  shell: gpg --import {{ ansible_env.PWD }}/roles/aaron_osx/files/keepassx/keepassx-public-key-83135D45.asc
  when: keepassx_exists.stat.exists == False

- name: Download KeePassX-2.0.3.dmg
  get_url:
    url: https://www.keepassx.org/releases/2.0.3/KeePassX-2.0.3.dmg
    dest: /tmp/KeePassX-2.0.3.dmg
  when: keepassx_exists.stat.exists == False

- name: Verify signature
  shell: gpg --verify {{ ansible_env.PWD }}/roles/aaron_osx/files/keepassx/KeePassX-2.0.3.dmg.sig /tmp/KeePassX-2.0.3.dmg
  register: keepassx_verify_sig_output
  failed_when: >
    'Good signature from "Felix Geyer <felix@fobos.de>"'
    not in keepassx_verify_sig_output.stderr
  when: keepassx_exists.stat.exists == False

- command: hdiutil attach /tmp/KeePassX-2.0.3.dmg -nobrowse -mountpoint /tmp/KeePassX-2.0.3
  when: keepassx_exists.stat.exists == False

- shell: cp -aR /tmp/KeePassX-2.0.3/KeePassX.app /Applications/KeePassX.app
  when: keepassx_exists.stat.exists == False

- command: hdiutil detach /tmp/KeePassX-2.0.3/
  when: keepassx_exists.stat.exists == False
# End keepassx installation
