# Install apt keys and repositories
- apt_key:
    url: '{{ item }}'
  with_items: '{{ apt_keys }}'
  become: true
  tags: apt

- apt_repository:
    repo: '{{ item }}'
  with_items: '{{ apt_repositories }}'
  become: true
  tags: apt

# Install apt packages
- apt:
    name: '{{ item }}'
  with_items: '{{ apt_packages }}'
  become: true
  tags: apt

# Install deb packages from uris
- name: check if deb packages already installed
  shell: dpkg -s '{{ item.name }}' | grep 'install ok installed' || true
  with_items: '{{ deb_uris }}'
  register: deb_uris_check_result
  tags: apt

- name: install missing deb packages
  apt:
    deb: '{{ item.1.uri }}'
  with_indexed_items: '{{ deb_uris }}'
  when: deb_uris_check_result.results[{{ item.0 }}].stdout == ""
  become: true
  tags: apt

# Install zplug (don't have brew here)
- name: install zplug
  git:
    repo: 'https://github.com/zplug/zplug'
    dest: ~/.zplug
